# server:
#   port: 9002


# spring:
#   application:
#     name: EurekaCustomer-Service
#   config:
#     import: optional:configserver:http://localhost:8085


# #eureka:
# #  instance:
# #    hostname: localhost
